# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stress <- function(x, W, D) {
    .Call('_smglr_stress', PACKAGE = 'smglr', x, W, D)
}

stress_major <- function(y, W, D, iter, tol) {
    .Call('_smglr_stress_major', PACKAGE = 'smglr', y, W, D, iter, tol)
}

